-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "ac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "distanceKm" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "occupancyType" TEXT NOT NULL DEFAULT 'unknown',
ADD COLUMN     "rent" INTEGER NOT NULL DEFAULT 0;
